---
name: Story/Task/Issue
description: Create a new story or task
body:
  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done / Acceptance Criteria
      description: What can someone see/do when this task is done.
      placeholder: >-
        The export data is available in the xxx format, including age of the
        patient at the time of imaging...
    validations:
      required: true
  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: Specific testing considerations for this task to be done
      placeholder: Passed integration testing that uses the correct modality...
    validations:
      required: false
  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: Documentation to be completed along with this task
      placeholder: Update README and user guide...
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: >-
        Enter the github issue number(s) that the requirement is dependent on,
        in the form `#1`
      placeholder: "#1"
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Any other considerations or comments
      placeholder: More details or other comments...
    validations:
      required: false
