---
name: New issue
description: Create a new story or task
body:
  - type: textarea
    id: definition_of_done
    attributes:
      label: Definition of Done
      description: How can others tell when this task is done?
      placeholder: >-
        The export data is available in X format, with Y processing and Z plots.
    validations:
      required: true
  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: Any testing considerations that should be taken into account
      placeholder: Unit, integration and regression tests will be written for feature X.
    validations:
      required: false
  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: Documentation to be completed or updated
      placeholder: README should be updated to reflect the changes. A wiki entry should be made.
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: >-
        Enter the github issue number(s) that the requirement is dependent on,
        in the form `#1`
      placeholder: "#1"
    validations:
      required: false
  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Any other considerations or comments
      placeholder: More details or other comments...
    validations:
      required: false
